language: android
jdk: oraclejdk7

env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-20  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-13  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-12  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-11  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-10  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-9  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-8  ANDROID_ABI=armeabi-v7a


android:
  components:
    - build-tools-23.0.2
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    - android-23
    - android-22
    - android-21
    - android-20
    - android-19
    - android-18
    - android-17
    - android-16
    - android-15
    - android-14
    - android-13
    - android-12
    - android-11
    - android-10
    - android-9
    - android-8
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-20
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-15
    - sys-img-armeabi-v7a-android-14
    - sys-img-armeabi-v7a-android-13
    - sys-img-armeabi-v7a-android-12
    - sys-img-armeabi-v7a-android-11
    - sys-img-armeabi-v7a-android-10
    - sys-img-armeabi-v7a-android-9
    - sys-img-armeabi-v7a-android-8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assemble lint

after_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
